### ISSUE TITLE
Portable Build Tools install fails

### ISSUE THREAD

**Issue by SirWrexes** [milnak/scoop-bucket#1]
Hey, I came from https://github.com/ScoopInstaller/Extras/issues/13027#issuecomment-2165970452
Thanks for the package! However, I'm getting this error during post-install:
```
PS C:\Users\Wrexes\scoop> scoop install portable-build-tools
Installing 'portable-build-tools' (2.4) [64bit] from 'milnak' bucket
PortableBuildTools.exe (138.0 KB) [===========================================================================] 100%
Checking hash of PortableBuildTools.exe ... ok.
Linking ~\scoop\apps\portable-build-tools\current => ~\scoop\apps\portable-build-tools\2.4
Running post_install script...portablebuildtools.exe : The term 'portablebuildtools.exe' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At line:1 char:1
+ portablebuildtools.exe accept_license target=x64 host=x64 env=user pa ...
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (portablebuildtools.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

WARNING: Running PortableBuildTools failed. Installation incomplete.
Out-File : Could not find a part of the path 'C:\BuildTools\devcmd.ps1'.
At line:33 char:6
+ '@ | Out-File (Join-Path 'c:\BuildTools' 'devcmd.ps1') -Encoding asci ...
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], DirectoryNotFoundException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand

done.
'portable-build-tools' (2.4) was installed successfully!
Notes
-----
To initialize build environment, run C:\BuildTools\devcmd.ps1
```

I thought "maybe I need to initialize the environment and try again for a fully functional install" but...
```
PS C:\Users\Wrexes\scoop> cat  C:\BuildTools\devcmd.ps1
cat : Cannot find path 'C:\BuildTools\devcmd.ps1' because it does not exist.
At line:1 char:1
+ cat  C:\BuildTools\devcmd.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\BuildTools\devcmd.ps1:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand
```

P.S. Sligthly unrelated question: Does it _need_ to be installed in `C:\` ? Or would there be a possiblity for a more "soopey" install, having it be inside `~/scoop` ?
Knowing how Windows does things, I fear the answer is no, though.

**Comment by milnak** [comment]
can you send the output of 

```Powershell
ls ~\scoop\apps\portable-build-tools\current
```

**Comment by milnak** [comment]
I also tried installing it under scoop, but there's [a bug](https://github.com/Data-Oriented-House/PortableBuildTools/issues/22) preventing that.

**Comment by SirWrexes** [comment]
> can you send the output of
> 
> ```powershell
> ls ~\scoop\apps\portable-build-tools\current
> ```
![image](https://github.com/user-attachments/assets/8c01f3c5-38b8-4851-86a4-832304f293a2)

**Comment by milnak** [comment]
I set up a VM for a clean install and have a repro. Working on a fix. Thanks for reporting!

**Comment by milnak** [comment]
I fixed this issue.  Please update `scoop update *` and try again.

**Comment by SirWrexes** [comment]
Will do an report back next time I have to boot on Windows! :saluting_face:

**Comment by milnak** [comment]
found root cause. I now install to `~\scoop\apps\portable-build-tools\current\bin`

**Comment by SirWrexes** [comment]
Woops, sorry this thread slipped my memory.
Coming here to confirm I've been able to install your package successfully, thanks a bunch !
